files = [
    "./parts/Введение.md",
    "./parts/Теоретическая часть.md",
    "./parts/Практическая часть.md",
    "./parts/Заключение.md",
    "./parts/Приложение. Код программы.md",
    "./parts/Приложение. Скрин.md",
]
